# Generated by Django 4.2.4 on 2023-08-18 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('code', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('image', models.CharField(max_length=150)),
                ('discount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_offer', models.ManyToManyField(to='offers.offer')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('enquiry_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.enquiry')),
                ('reply_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.student')),
            ],
        ),
        migrations.AddField(
            model_name='enquiry',
            name='enquiry_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.student'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='offer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.offer'),
        ),
        migrations.CreateModel(
            name='BookingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_applied', models.BooleanField(default=False)),
                ('price', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('total_passenger', models.IntegerField()),
                ('booked_on', models.DateField()),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.flight')),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='offers.offer')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
