# Generated by Django 4.2.4 on 2023-08-19 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
