# Generated by Django 4.2.4 on 2023-08-19 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('offers', '0002_offer_is_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='enquiry_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.userinfo'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='reply_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.userinfo'),
        ),
    ]
