# Generated by Django 4.2.4 on 2023-08-18 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('departure', models.TimeField()),
                ('arrival', models.TimeField()),
                ('fare', models.IntegerField()),
                ('flight_from', models.CharField(max_length=60)),
                ('flight_to', models.CharField(max_length=60)),
                ('flight_class', models.CharField(max_length=60)),
                ('flight_code', models.CharField(max_length=60)),
                ('flight_pnr', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(max_length=20)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
